config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :employees

  get 'info/index'

  get 'employees/index/:page' => "employee#index"
  
  root :to => 'employees#index'

  match 'search' => 'employees#search', :via => :post
  
  match 'kanri_search' => 'employees#kanri_search', :via => :post
  
  get 'kanri' => 'employees#kanri'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
 mount_uploader :image, ImageUploader
 scope :search_names_or, lambda { |search_word| where("name like ? or zaseki like ? or job like ? or project like ? or shumi like ? or game like ? or furigana like ? or mail like? or jico like? ", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%") }
end

app/models/member.rb
class Member < ActiveRecord::Base
  mount_uploader :image, ImageUploader
#  attr_protected :id
  scope :search_names_or, lambda { |search_word| where("name like ? or company like ? or job like ?", "%#{search_word}%", "%#{search_word}%" ,"%#{search_word}%") }
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zaseki.rb
class Zaseki < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#before_action :authenticate_admin!
before_action :authenticate_admin!, except: [:index]
before_action :authenticate_admin!, only: [:kanri]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def after_sign_in_path_for(resource)
    '/kanri'
  end   

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

#layout/kanri.html.erbを使用するアクション指定
  layout "kanri", :only => [:kanri, :kanri_search]

  def index
#    @employees = Employee.all
    @employees = Employee.page(params[:page]).per(20).order(:id)
    respond_with(@employees)
  end
  
  def kanri
     @employees = Employee.all.page(params[:page]).per(20).order(:id)
     respond_with(@employees) 
  end
  
  def show
    respond_with(@employee)
  end

   def search
      @employees = Employee.search_names_or(params[:stxt])
   end

   def kanri_search
      @employees = Employee.search_names_or(params[:stxt])
      render :kanri
   end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with(@employee)
#      ChatWork.api_key = "66496d47070398f1824d380bbebbcdfe"
#      ChatWork::Message.create(room_id: 5565940, body: "新しい従業員が追加されました! プロフィール写真はご自身で設定可能ですhttp://1717.applibot.co.jp/")
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
#    respond_with(@employee)
#    render kanri
   redirect_to :action => "kanri" 
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :zaseki, :about, :job, :project, :pc, :notepc, :shumi, :game, :furigana, :mail, :jico, :nyusha, :koyo, :kingaku, :itaku, :image, :image_cache, :remove_image)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/zasekis_controller.rb
class ZasekisController < ApplicationController
  before_action :set_zaseki, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @zasekis = Zaseki.all
    respond_with(@zasekis)
  end

  def show
    respond_with(@zaseki)
  end

  def new
    @zaseki = Zaseki.new
    respond_with(@zaseki)
  end

  def edit
  end

  def create
    @zaseki = Zaseki.new(zaseki_params)
    @zaseki.save
    respond_with(@zaseki)
  end

  def update
    @zaseki.update(zaseki_params)
    respond_with(@zaseki)
  end

  def destroy
    @zaseki.destroy
    respond_with(@zaseki)
  end

  private
    def set_zaseki
      @zaseki = Zaseki.find(params[:id])
    end

    def zaseki_params
      params.require(:zaseki).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/zasekis_helper.rb
module ZasekisHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :label => '氏名' %>
    <%= f.input :furigana, :label => 'フリガナ' %>
    <%= f.input :zaseki, :label => '座席番号' %>
    <%= f.input :mail, :label => 'メール' %>
    <%= f.input :about, :label => '社員番号' %>
    <%= f.input :job, :label => '職種' %>
    <%= f.input :project, :label => 'プロジェクト' %>
    <p>自己紹介</p>
    <%= f.text_area :jico, :label => '自己紹介', :size=>"200x10" %>  
</div>

<!-- 追加箇所 開始 -->
  <div class="field">
    <% if @employee.image? %>
      <div class="thumbnail">
        <%= image_tag @employee.image.url %>
      </div>
    <% end %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @employee.persisted? && @employee.image? %>
      <label>
        <%= f.check_box :remove_image %>
        画像を削除
      </label>
    <% end %>
  </div>
  <!-- 追加箇所 終了 -->

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/_form_kanri.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :label => '氏名' %>
    <%= f.input :furigana, :label => 'フリガナ' %>
    <%= f.input :zaseki, :label => '座席番号' %>
    <%= f.input :mail, :label => 'メール' %>
    <%= f.input :about, :label => '社員番号' %>
    <%= f.input :job, :label => '職種' %>
    <%= f.input :project, :label => 'プロジェクト' %>
    <%= f.input :project, :label => 'プロジェクト' %>
    <p>自己紹介</p>
    <%= f.text_area :jico, :label => '自己紹介', :size=>"200x10" %>  
</div>

<!-- 追加箇所 開始 -->
  <div class="field">
    <% if @employee.image? %>
      <div class="thumbnail">
        <%= image_tag @employee.image.url %>
      </div>
    <% end %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @employee.persisted? && @employee.image? %>
      <label>
        <%= f.check_box :remove_image %>
        画像を削除
      </label>
    <% end %>
  </div>
  <!-- 追加箇所 終了 -->

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>更新</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>メンバー＆座席表</h1>
<center><h1>1717 Member list</h1></center>
	
<%= paginate(@employees) %>
<div class="container">
<div class="tablecenter">
<table class="span11 table table-striped table-bordered table-hover table-condensed table-responsive yokohaba" >
  <thead class="scrollHead">
    <tr class="active">
      <th width="80">Picture</th>
      <th width="80">氏名</th>
      <th width="80">座席</th>
      <th width="280">メール</th>
      <th width="80">社員番号</th>
      <th width="200">職種</th>
      <th width="80">プロジェクト</th>
      <th width="80">管理</th>
    </tr>

  </thead>

  <tbody class="scrollBody">
    <% @employees.each do |employee| %>
      <tr>
        <td><image src="<%= employee.image %>" width="80" height="50"></td>
        <td width="80"><%= employee.name %></td>
        <td width="80"><%= employee.zaseki %></td>
        <td width="280"><%= employee.mail %></td>
        <td width="80"><%= employee.about %></td>
        <td width="200"><%= employee.job %></td>
        <td width="80"><%= employee.project %></td>
        <td><button type="button" class="btn btn-info" ><%= link_to '参照', employee %></td></button>
        <td><button type="button" class="btn btn-warning" ><%= link_to '更新', edit_employee_path(employee) %></button></td>
<!--        <td><button type="button" class="btn btn-danger" ><%= link_to '削除', employee, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
-->

      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<p class="fixed-0">
<button type="button" class="btn btn-success" ><%= link_to 'New Member', new_employee_path %></button>
</p>

app/views/employees/kanri.html.erb
<p id="notice"><%= notice %></p>

<h1>従業員＆座席表</h1>
<center><h1>1717 Memeber list</h1></center>
<div class="container">
<div class="tablecenter">
<table class="span11 table table-striped table-bordered table-hover table-condensed table-responsive yokohaba-kanri">
  <thead class="scrollHead">
    <tr class="active">
      <th width="80">Picture</th>
      <th width="80">氏名</th>
      <th width="80">座席</th>
      <th width="280">メール</th>
      <th width="80">社員番号</th>
      <th width="200">職種</th>
      <th width="80">プロジェクト</th>
      <th width="80">入社日</th>
      <th width="80">雇用形態</th>
      <th width="80">委託元</th>
      <th width="80">金額</th>
      <th width="80">管理</th>
    </tr>

  </thead>

  <tbody class="scrollBody">
    <% @employees.each do |employee| %>
      <tr>
        <td><image src="<%= employee.image %>" width="80" height="50"></td>
        <td width="80"><%= employee.name %></td>
        <td width="80"><%= employee.zaseki %></td>
        <td width="280"><%= employee.mail %></td>
        <td width="80"><%= employee.about %></td>
        <td width="200"><%= employee.job %></td>
        <td width="80"><%= employee.project %></td>
        <td width="80"><%= employee.nyusha %></td>
        <td width="80"><%= employee.koyo %></td>
        <td width="80"><%= employee.itaku %></td>
        <td width="80"><%= employee.kingaku %></td>
        <td><button type="button" class="btn btn-info" ><%= link_to '参照', employee %></td></button>
        <td><button type="button" class="btn btn-warning" ><%= link_to '更新', edit_employee_path(employee) %></button></td>
        <td><button type="button" class="btn btn-danger" ><%= link_to '削除', employee, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>


      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<p class="fixed-0">
<button type="button" class="btn btn-success" ><%= link_to 'New Member', new_employee_path %></button>
</p>

app/views/employees/kanrimeibo.html.erb
<p id="notice"><%= notice %></p>

<h1>従業員＆座席表</h1>
<center><h1>1717 Memeber list</h1></center>
<div class="container">
<div class="tablecenter">
<table class="span11 table table-striped table-bordered table-hover table-condensed table-responsive yokohaba" >
  <thead class="scrollHead">
    <tr class="active">
      <th width="80">Picture</th>
      <th width="80">氏名</th>
      <th width="80">座席</th>
      <th width="280">メール</th>
      <th width="80">社員番号</th>
      <th width="200">職種</th>
      <th width="80">プロジェクト</th>
      <th width="80">管理</th>
    </tr>

  </thead>

  <tbody class="scrollBody">
    <% @employees.each do |employee| %>
      <tr>
        <td><image src="<%= employee.image %>" width="80" height="50"></td>
        <td width="80"><%= employee.name %></td>
        <td width="80"><%= employee.zaseki %></td>
        <td width="280"><%= employee.mail %></td>
        <td width="80"><%= employee.about %></td>
        <td width="200"><%= employee.job %></td>
        <td width="80"><%= employee.project %></td>
        <td><button type="button" class="btn btn-info" ><%= link_to '参照', employee %></td></button>
        <td><button type="button" class="btn btn-warning" ><%= link_to '更新', edit_employee_path(employee) %></button></td>
        <td><button type="button" class="btn btn-danger" ><%= link_to '削除', employee, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<p class="fixed-0">
<button type="button" class="btn btn-success" ><%= link_to 'New Member', new_employee_path %></button>
</p>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/search.html.erb
<p id="notice"><%= notice %></p>

<h1>メンバー＆座席表</h1>
<center><h1>1717 Member list</h1></center>
	
<div class="container">
<div class="tablecenter">
<table class="span11 table table-striped table-bordered table-hover table-condensed table-responsive yokohaba" >
  <thead class="scrollHead">
    <tr class="active">
      <th width="80">Picture</th>
      <th width="80">氏名</th>
      <th width="80">座席</th>
      <th width="280">メール</th>
      <th width="80">社員番号</th>
      <th width="200">職種</th>
      <th width="80">プロジェクト</th>
      <th width="80">管理</th>
    </tr>

  </thead>

  <tbody class="scrollBody">
    <% @employees.each do |employee| %>
      <tr>
        <td><image src="<%= employee.image %>" width="80" height="50"></td>
        <td width="80"><%= employee.name %></td>
        <td width="80"><%= employee.zaseki %></td>
        <td width="280"><%= employee.mail %></td>
        <td width="80"><%= employee.about %></td>
        <td width="200"><%= employee.job %></td>
        <td width="80"><%= employee.project %></td>
        <td><button type="button" class="btn btn-info" ><%= link_to '参照', employee %></td></button>
        <td><button type="button" class="btn btn-warning" ><%= link_to '更新', edit_employee_path(employee) %></button></td>
<!--        <td><button type="button" class="btn btn-danger" ><%= link_to '削除', employee, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
-->

      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<p class="fixed-0">
<button type="button" class="btn btn-success" ><%= link_to 'New Member', new_employee_path %></button>
</p>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>氏名:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>座席:</strong>
  <%= @employee.zaseki %>
</p>

<p>
  <strong>社員番号:</strong>
  <%= @employee.about %>
</p>

<p>
  <strong>職種:</strong>
  <%= @employee.job %>
</p>

<p>
  <strong>プロジェクト:</strong>
  <%= @employee.project %>
</p>

<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <strong>自己紹介:</strong>
    </div>
    <div class="col-xs-4">
      <%= @employee.jico %>
    </div>
  </div>
</div>
<br>
<!-- 追加箇所 開始 -->
<p>
  <strong>写真:</strong>
  <% if @employee.image? %>
    <div class="thumbnail">
      <%= image_tag @employee.image.url %>
    </div>
  <% end %>
</p>
<!-- 追加箇所 終了 -->

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/info/index.html.erb
test

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="http://1717.applibot.co.jp/">Applibot</a>
        <div class="nav-collapse">
        <ul class="nav">
	<div class="btn-group">
        <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        座席表<span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="http://1717.applibot.co.jp/assets/1f.pdf">1F</a></li>
          <li><a href="http://1717.applibot.co.jp/assets/2f.pdf">2F</a></li>
          <li><a href="http://1717.applibot.co.jp/assets/3f.pdf">3F</a></li>
          <li><a href="http://1717.applibot.co.jp/assets/4f.pdf">4F</a></li>
        </ul>
      </div>
<!--              <li><%= link_to "Sign Out", destroy_admin_session_path%></li>
--!>
          </ul>
            <form class="navbar-form navbar-right" role="search" method="post" action="/search">
            <div class="form-group">
            <input name="stxt" type="text" class="form-control" placeholder="検索条件を入れてください">
            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
            <button type="submit" class="btn btn-default">検索</button>
            </div>
          </form>
<!--                <li><%= link_to "Sign In", new_admin_session_path%></li>
-->                </ul>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_header_emp.html.erb
<header>
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="http://http://54.65.194.180/employees">ApplibotMembers</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Member_list", 'http://http://54.65.194.180/employees/' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_header_kanri.html.erb
<header>
  <div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="http://1717.applibot.co.jp/">Applibot</a>
        <div class="nav-collapse">
        <ul class="nav">
	<div class="btn-group">
        <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        座席表<span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="http://1717.applibot.co.jp/assets/1f.pdf">1F</a></li>
          <li><a href="http://1717.applibot.co.jp/assets/2f.pdf">2F</a></li>
          <li><a href="http://1717.applibot.co.jp/assets/3f.pdf">3F</a></li>
          <li><a href="http://1717.applibot.co.jp/assets/4f.pdf">4F</a></li>
        </ul>
      </div>
<!--              <li><%= link_to "Sign Out", destroy_admin_session_path%></li>
--!>
          </ul>
            <form class="navbar-form navbar-right" role="kanri_search" method="post" action="/kanri_search">
            <div class="form-group">
            <input name="stxt" type="text" class="form-control" placeholder="検索条件を入れてください">
            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
            <button type="submit" class="btn btn-default">検索</button>
            </div>
          </form>
<!--                <li><%= link_to "Sign In", new_admin_session_path%></li>
-->                </ul>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Applibot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/header' %>     
 <%= yield %>
</body>
</html>

app/views/layouts/kanri.html.erb
<html>
<head>
  <title>Applibot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/header_kanri' %>     
 <%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/zasekis/_form.html.erb
<%= simple_form_for(@zaseki) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/zasekis/edit.html.erb
<h1>Editing Zaseki</h1>

<%= render 'form' %>

<%= link_to 'Show', @zaseki %> |
<%= link_to 'Back', zasekis_path %>

app/views/zasekis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zasekis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zasekis.each do |zaseki| %>
      <tr>
        <td><%= zaseki.name %></td>
        <td><%= zaseki.address %></td>
        <td><%= link_to 'Show', zaseki %></td>
        <td><%= link_to 'Edit', edit_zaseki_path(zaseki) %></td>
        <td><%= link_to 'Destroy', zaseki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zaseki', new_zaseki_path %>

app/views/zasekis/new.html.erb
<h1>New Zaseki</h1>

<%= render 'form' %>

<%= link_to 'Back', zasekis_path %>

app/views/zasekis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zaseki.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @zaseki.address %>
</p>

<%= link_to 'Edit', edit_zaseki_path(@zaseki) %> |
<%= link_to 'Back', zasekis_path %>